local router = require "modules.router"

function init(self)
	msg.post(".", "acquire_input_focus")
	router.go("home")
end

function on_message(self, message_id, message, sender)
	if router.on_message(message_id, message, sender) then
		return
	end
end

function on_input(self, action_id, action)
	if router.current then
		msg.post(router.current, "input", { action_id = action_id, action = action })
	end
end